### ISSUE TITLE
Google Analytics / Matomo

### ISSUE THREAD

**Issue by caprenter** [caprenter/shipley-film-society#20]
I think there is a place holder in the code for this, but we've not plugged values in.

- [ ] check to see if the old site had it in place
- [ ] if so, find the google account
- [ ] decide if we want to reimplement it

**Comment by caprenter** [comment]
From @caffiendcode 

I'd been thinking about the Google analytics issue yesterday. The old site did seem to have Google analytics integration. If you search for gTag you'll see the stuff relating to G Analytics I think.

Thinking of the privacy of users I'd like to assess open-source solutions. I don't think we'd lose anything in visibility and we might gain better visibility, in some regards, with some options. I began looking into those options and started SWOT analysis which I can't yet share as I haven't populated my diagrams.

https://matomo.org/ seems to be feature-rich but has to be self-hosted and requires machine resources (would run on a Pi but might eat at least half of the Pi)

https://goaccess.io/ sounded interesting, lightweight, is terminal-based

https://www.goatcounter.com/ & https://count.ly/ are free SAAS for not-for-profit use.

I've a Pi I'm not using and might be happy to donate but haven't tried hosting on it and my broadband's my mobile phone hotspot. I don't know if that could even work but if it could I think it might be fun to try.

**Comment by caprenter** [comment]
Brilliant - yes I'd prefer something like this.

I can see Matamo used t be Piwik and my previous organisation used this.

The person I work with now is a big docker fan and we probably need a similar analytics tool for some other projects. I'll see if we can maybe have a go at setting up an instance. But you carry on for now...

NB My plan is to host the site via GitHub pages still, so a solution that is NOT on the same server as the website would be preffered - if we really needed to I guess we could FTP the site somewhere else.

**Comment by caprenter** [comment]
We can use the Cooperative IT matomo instance for this. I'll get that set up at somepoint

**Comment by caffiendcode** [comment]
nice

-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



28 Sept 2022, 09:25 by ***@***.***:

**Comment by caprenter** [comment]
Closing this as done
