### ISSUE TITLE
Past Films- Data

### ISSUE THREAD

**Issue by caprenter** [caprenter/shipley-film-society#79]
Thinking that on a film that is in the past, we don't need all the information.

Certainly not the doors information, probably not the price (although that might be nice)

So  a mock up of a past film page could be step one.

I guess we would need an update routine that goes:
Regenerate site (e.g. with a new film)
Work out which film is now in the past and regenerate that film page (noting that while it is still upcoming it needs the doors and price info)

So e.g. 
when updating 9-5 this month, we would also have had to 
delete _/films/8women
regenerate the film list
as part of our update routine

I'm not sure if the film page building script can tell if a film is past or future?

**Comment by caffiendcode** [comment]
Think this can be closed. Added a related readme section under this issue.
