### ISSUE TITLE
Version 2.0 of the website

### ISSUE THREAD

**Issue by caprenter** [caprenter/shipley-film-society#8]
I'm wondering if a version 2 of the website with a more conventional menu system and less 'loading' is worth building.

The + Film Menu is not that intuitive - and it's more than a film menu - it's everything.

It probably needs some semi-serous scoping.
(I like that 'Next showing' is easy to get to )

**Comment by caprenter** [comment]
A couple of things to remember:

We probably only show 6-10 films in a season - so it doesn't need a complicated listing.

We want to highlight the next film that will be shown. I quite like this site for that:https://www.newcastlecinema.org/

I quite like this look for a list of films: https://www.richmondfilmsoc.org.uk/

And here is a list of community cinemas to look through for ideas: https://mycommunitycinema.org.uk/cinemas/

**Comment by caprenter** [comment]
@caffiendcode I've checked in a branch called version2, that uses the Jasper theme. 
https://github.com/caprenter/shipley-film-society/tree/version2

Done some very simple stuff with _data to get info on the front page.

See what you think. 
NB when you check it out you may need to follow the README_Jasper.md docs to update your gems - but it should run!

**Comment by caffiendcode** [comment]
Had to faff with my VM to install the dependencies to run your branch. I can serve the site locally although it doesn't look fully wired together yet. New theme seems a lot snappier. I've jotted down some scraps which can be added to the README. I'm using ruby 2.72 now, is that what you're using? Should be able to get hacking properly tomorrow evening.

-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



20 Jul 2022, 19:36 by ***@***.***:

**Comment by caprenter** [comment]
Closing this as we've now got version 2 deployed

**Comment by caprenter** [comment]
Thanks Haba

So Ruby:
ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

Sorry you had to mess with your VM. Yes please to adding some bits to the
readme!

I think the new site is worth persisting with at the moment - what do you
think?

Some notes:

The new site is just:
Logo, Site title
Main image
Demo of how a film listing could look

I've removed all/most of the demo content that came with the Jasper theme,
so pages linked from the menu, some images etc will be broken.

I've been thinking overnight a bit, so my plan today if i get some time is
to try to add some of the old content - about, contact, home page content,
and see how it feels.

I really like the 'Our next Film is" being the main thing you see when you
arrive.

(But was also thinking this will need to change in March as we might not
have films until October!)

Cheers
David

**Comment by caffiendcode** [comment]
Ah cool thanks. Got a bit of work to catch up on but expect time to do the merge thing this week or the weekend. 
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



11 Oct 2022, 08:55 by ***@***.***:

>
>
>
> Thanks Haba
>  
>  So Ruby:
>  ruby -v
>  ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
>  
>  Sorry you had to mess with your VM. Yes please to adding some bits to the
>  readme!
>  
>  I think the new site is worth persisting with at the moment - what do you
>  think?
>  
>  Some notes:
>  
>  The new site is just:
>  Logo, Site title
>  Main image
>  Demo of how a film listing could look
>  
>  I've removed all/most of the demo content that came with the Jasper theme,
>  so pages linked from the menu, some images etc will be broken.
>  
>  I've been thinking overnight a bit, so my plan today if i get some time is
>  to try to add some of the old content - about, contact, home page content,
>  and see how it feels.
>  
>  I really like the 'Our next Film is" being the main thing you see when you
>  arrive.
>  
>  (But was also thinking this will need to change in March as we might not
>  have films until October!)
>  
>  Cheers
>  David
>  
>  
>
